version: '3'

services:
  letter_mcp:
    build:
      context: .
      dockerfile: Dockerfile
    image: letter_mcp:latest
    container_name: letter_mcp
    ports:
      - "${PORT:-8080}:8080"
    environment:
      - PORT=${PORT:-8080}
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs 