# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM golang:1.24-alpine AS builder

WORKDIR /app

# Copy go.mod and go.sum first for caching dependencies
COPY go.mod go.sum ./

# Download dependencies
RUN go mod download

# Copy the source code
COPY . .

# Build the application
RUN go build -ldflags="-s -w" -o letter_mcp .

FROM alpine:latest

WORKDIR /app

# Copy the built binary from the builder stage
COPY --from=builder /app/letter_mcp ./

# Создаем директорию для логов
RUN mkdir -p /app/logs

# Установка переменной окружения для порта (по умолчанию 8080)
ENV PORT=8080

# Запуск сервера через SSE с заданным портом
ENTRYPOINT ["sh", "-c", "./letter_mcp -t sse"]